### PR TITLE
Replace search area string with SearchArea enum

### PR DESCRIPTION
**Pull request by eupn**
Make the code less error-prone by limiting the user's input.

### CODE REVIEW

**Review by spenserblack — CHANGES_REQUESTED** [review]
Thanks for the PR!

I understand why you would want to have a user pass an `enum`; I debated whether or not to do so myself. I decided against it because it's simply easier for a user to pass a string. Less documentation to reference, no need to be familiar with enum variants, less imports.

Your PR has made me reconsider this issue, though. Instead of passing an `enum`, perhaps the proper way would be to have multiple constructing functions for `Search`. So this would be the new usage:
```rust
Search::issues(&Query::new()/*etc*/)
```
Which would store the `SearchArea` (not public) behind the scenes.

What do you think about this?

**Comment by eupn** [comment]
@spenserblack yeah, this will do the job! This is more about how one wants to settle in a design decision space. To reduce the end user's burden with additional enums, sure we can hide them internally and use the constructor instead to still be able to restrict the user from providing invalid "area" value.

**Comment by spenserblack** [comment]
On second thought, `Search` itself can be an `enum`.

**Comment by spenserblack** [comment]
Hi @eupn!
I just pushed up a commit that fixed this, but if you still want to work on this type of thing, I've created #25

**Pull request closed without merging**
